# .streamlit/secrets.toml

# Khóa API này chỉ là placeholders (giá trị giữ chỗ)
# Không đặt khóa API thực tế của bạn tại đây để tránh lộ ra công khai!
GEMINI_API_KEY = "AIzaSyB0bnpbOu8GHo59Z6hxpypDeA-I_vROWc0"

# Nếu bạn có các bí mật khác
# DB_PASSWORD = "dummy_db_password"
